; ---------------------------------------------------------------------------
; Constants
; ---------------------------------------------------------------------------

; Background music
bgm_Mountain	= $83 ; 0
bgm_Desert	= $83 ; 1
bgm_Sky		= $83 ; 2
bgm_Ice		= $82 ; 3
bgm_Hills	= $83 ; 4
bgm_Ending	= $83 ; 5
bgm_Forest	= $83 ; 6
bgm_Cave	= $83 ; 7
bgm_Island	= $83 ; 8
bgm_Murderwall	= $83 ; 9
bgm_Swamp	= $83 ; $A
bgm_City	= $83 ; $65
bgm_Score_Board	= $83 ; $74

; Sound effects
sfx_Socre_counter		= 0 ; $C
sfx_Block_hit			= $AB ; $D
sfx_Clock_prize			= $A5 ; $E
sfx_Destroy_block		= $AB ; $11
sfx_Prize_block			= $A5 ; $11
sfx_Reveal_Hidden_block		= 0 ; $12 ; duplicate
sfx_Metal_block			= 0 ; $12 ; duplicate
sfx_Evanescent_block		= 0 ; $14
sfx_Shifting_block		= 0 ; $15
sfx_Jump			= $A0 ; $17
sfx_Lava_Geyser_starting	= 0 ; $1E ; duplicate
sfx_Lava_Geyser			= 0 ; $1E ; duplicate
sfx_Elevator_block		= 0 ; $27
sfx_Diamond_Power_available	= 0 ; $28
sfx_Ankh_prize			= 0 ; $29
sfx_Replenish_Health		= 0 ; $2A
sfx_Coin_prize			= $A5 ; $2C
sfx_Diamond_prize		= $A5 ; $2D ; duplicate
sfx_Navigate_jingle		= 0 ; $2D ; duplicate
sfx_Jump_on_enemy		= $A4 ; $4C
sfx_Voice_no_time		= 0 ; $51
sfx_Rubber_block		= 0 ; $56
sfx_Voice_die			= $A3 ; $60
sfx_Voice_ouch			= $A3 ; $61
sfx_Voice_diamond		= 0 ; $62
sfx_Voice_bummer		= $A3 ; $68
sfx_Voice_ouch_1		= $A3 ; $6B ; original recording
sfx_Voice_ouch_2		= $A3 ; $6C ; slowed down
sfx_Voice_ouch_3		= $A3 ; $6D ; slowed down
sfx_Teleport			= 0 ; $76
sfx_Thunderstorm		= 0 ; $77

; Sound effects characters
sfx_The_Kid_pullup			= 0 ; $64
sfx_Iron_Knight_transform		= 0 ; $1A
sfx_Iron_Knight_wall_climbing		= 0 ; $1C
sfx_Maniaxe_transform			= 0 ; $1B
sfx_Maniaxe_throw_axe			= 0 ; $20
sfx_Maniaxe_hitting_enemy		= 0 ; $4B
sfx_Red_Stealth_transform		= 0 ; $2E
sfx_Red_Stealth_attack_down		= 0 ; $13
sfx_Red_Stealth_sword_swinging		= 0 ; $23
sfx_Red_Stealth_hitting_a_target	= 0 ; $5A
sfx_Berzerker_transform			= 0 ; $2F
sfx_Berzerker_moving_block		= 0 ; $10
sfx_Skycutter_transform			= 0 ; $30
sfx_Skycutter_flipboard			= 0 ; $17
sfx_Eyeclops_transform			= 0 ; $31
sfx_Eyeclops_normal_lightbeam		= 0 ; $35
sfx_Eyeclops_hard_lightbeam		= 0 ; $3B
sfx_Cyclone_transform			= 0 ; $32
sfx_Micromax_transform			= 0 ; $33
sfx_Micromax_sticking			= 0 ; $22
sfx_Juggernaut_transform		= 0 ; $34
sfx_Juggernaut_skull_explode		= 0 ; $24
sfx_Juggernaut_shoot			= 0 ; $3E ; NO SOUND!

; Sound effects enemies
sfx_Drill_moving		= 0 ; $B
sfx_Robot_walking		= 0 ; $F ; Need to be located
sfx_UFO_hovering		= 0 ; $19
sfx_Tank_driving		= 0 ; $1F
sfx_Emo_Rock_disappears		= 0 ; $25
sfx_Big_Hopping_Skull_dies	= 0 ; $26
sfx_UFO_shoots			= 0 ; $3A ; duplicate
sfx_Robot_shoots		= 0 ; $3A ; duplicate
sfx_Tank_mouth_open		= 0 ; $3C
sfx_Mini_Hopping_Skull_screams	= 0 ; $3F
sfx_Tank_shoots			= 0 ; $41
sfx_Tank_mouth_closed		= 0 ; $42
sfx_Dragon_flame_breath		= 0 ; $46 ; NO SOUND!
sfx_Boss_eye_pops		= 0 ; $48
sfx_Plethora_x			= 0 ; $4E ; NO SOUND!
sfx_Ninja_blocking		= 0 ; $52
sfx_Tar_Monster_disappears	= 0 ; $53
sfx_Tar_Monster_appears		= 0 ; $54
sfx_Boss_dies			= 0 ; $57 ; duplicate
sfx_Drips_dripping		= 0 ; $58
sfx_Archer_shoots		= 0 ; $59
sfx_Big_Hopping_Skull_groan	= 0 ; $5C
sfx_Fireball_bouncing		= 0 ; $5D
sfx_Tar_Monster_shoots		= 0 ; $5E
sfx_Robot_jumping_on		= 0 ; $5F

; Weather
WeatherID_Lava	= 1
WeatherID_Storm	= 2
WeatherID_Storm_and_Hail	= 3

; Character movement
MoveID_Standingstill	= 0
MoveID_Crawling	= 1
MoveID_Walking	= 2
MoveID_Jump	= 3
MoveID_Wall_Climbing	= 4
MoveID_Up_Down_Hill	= 5

; Keystrokes
Button_Up	= 0
Button_Down	= 1
Button_Left	= 2
Button_Right	= 3
Button_B	= 4 ; jump
Button_C	= 5 ; special
Button_A	= 6 ; run
Button_Start	= 7

Button_Up_mask		=	1<<Button_Up	; $01
Button_Down_mask	=	1<<Button_Down	; $02
Button_Left_mask	=	1<<Button_Left	; $04
Button_Right_mask	=	1<<Button_Right	; $08
Button_B_mask		=	1<<Button_B	; $10
Button_C_mask		=	1<<Button_C	; $20
Button_A_mask		=	1<<Button_A	; $40
Button_Start_mask	=	1<<Button_Start	; $80


; Characters
The_Kid	= 0
Skycutter	= 1
Cyclone	= 2
Red_Stealth	= 3
Eyeclops	= 4
Juggernaut	= 5
Iron_Knight	= 6
Berzerker	= 7
Maniaxe	= 8
Micromax	= 9

; Themes
Theme_Unknown	= 0
Sky	= 1
Ice	= 2
Hills	= 3
Island	= 4
Desert	= 5
Swamp	= 6
Mountain	= 7
Cave	= 8
Forest	= 9
City	= $A

; Collision
colid_empty	= 0
colid_rightwall	= 4
colid_leftwall	= 8
colid_floor	= $C
colid_ceiling	= $10
colid_slopeup	= $14
colid_slopedown	= $18
colid_hurt	= $1C
colid_kidright	= $20
colid_kidleft	= $24
colid_kidbelow	= $28
colid_kidabove	= $2C

; enemy IDs
objid_FireDemon	= $00
objid_Diamond	= $01
objid_Robot	= $03
objid_Armadillo	= $04
objid_TarMonster	= $05
objid_Sphere	= $06
objid_Archer	= $07
objid_Orca	= $08
objid_Crab	= $09
objid_RockTank	= $0A
objid_RockTank_shooting	= $0B
objid_Dragon_flying	= $0C
objid_Dragon	= $0D
objid_Cloud	= $0E
objid_UFO	= $0F
objid_Goat	= $10
objid_Ninja	= $11
objid_Lion	= $12
objid_Scorpion	= $13
objid_SpinningTwins	= $14
objid_Drip	= $16
objid_Hand	= $17
objid_Tornado	= $18
objid_Fireball	= $19
objid_Driller	= $1A
objid_EmoRock	= $1B
objid_MiniHoppingSkull	= $1C
objid_BigHoppingSkull	= $1D
objid_invalid1F	= $1F
objid_HeadyMetal	= $20
objid_Shiskaboss	= $22
objid_BoomerangBosses	= $23
objid_BagelBrothers	= $24
;objid_?	= $3C
objid_prizediamond	= $64	; also ankh or clock after being collected
objid_skycutter	= $6C
objid_cyclone	= $70
objid_redstealth	= $74
objid_eyeclops	= $78
objid_juggernaut	= $7C
objid_ironknight	= $80
objid_berzerker	= $84
objid_maniaxe	= $88
objid_micromax	= $8C
objid_ankh	= $90
objid_clock	= $94
objid_continue	= $98
objid_unkprize	= $9C
objid_flagpole	= $A0
;objid_BagelBrothers2	= $A4 ; ($24 with bit 7 set)


; Levels by number
L_Blue_Lake_Woods_1	= 0
L_Blue_Lake_Woods_2	= 1
L_Highwater_Pass_1	= 2
L_Highwater_Pass_2	= 3
L_Under_Skull_Mountain_1	= 4
L_Under_Skull_Mountain_2	= 5
L_Under_Skull_Mountain_3	= 6
L_Isl_of_the_Lion_Lord	= 7
L_Hills_of_the_Warrior_1	= 8
L_Hills_of_the_Warrior_2	= 9
L_Wind_City	= $A
L_Sinister_Sewers	= $B
L_The_Crystal_Crags_1	= $C
L_The_Crystal_Crags_2	= $D
L_Dragonspike	= $E
L_Stormwalk_Mountain	= $F
L_Shishkaboss	= $10
L_The_Whispering_Woods_1	= $11
L_The_Whispering_Woods_2	= $12
L_Devils_March_1	= $13
L_Devils_March_2	= $14
L_Knights_Isle	= $15
L_Whale_Grotto	= $16
L_Hoverboard_Beach	= $17
L_Pyramids_of_Peril	= $18
L_Madmaze_Mountain	= $19
L_The_Deadly_Skyscrapers	= $1A
L_Skydragon_Castle_1	= $1B
L_Skydragon_Castle_2	= $1C
L_Coral_Blade_Grotto	= $1D
L_Boomerang_Bosses	= $1E
L_Woods_of_Despair_1	= $1F
L_Woods_of_Despair_2	= $20
L_Forced_Entry	= $21
L_The_Cliffs_of_Illusion	= $22
L_Lions_Den	= $23
L_Wind_Castles_1	= $24
L_Wind_Castles_2	= $25
L_Blizzard_Mountain	= $26
L_Caves_of_Ice	= $27
L_The_Nightmare_Peaks_1	= $28
L_The_Nightmare_Peaks_2	= $29
L_Bagel_Brothers	= $2A
L_Diamond_Edge	= $2B
L_The_Hills_Have_Eyes	= $2C
L_Secret_in_the_Rocks	= $2D
L_Ice_Gods_Vengeance	= $2E
L_Beneath_the_Twisted_Hills	= $2F
L_Alien_Isle	= $30
L_The_Land_Below	= $31
L_The_Final_Marathon	= $32
L_Plethora	= $33
L_The_Pinnacle	= $34
L_Hidden_Canyon	= $35
L_The_Caged_Beast	= $36
L_Crab_Cove	= $37
L_The_Crypt_38	= $38 ; unplayable
L_The_Forbidden_Tombs	= $39
L_Stairway_to_Obilivion	= $3A
L_The_Valley_of_Life	= $3B
L_The_Black_Pit	= $3C
L_Frosty_Doom	= $3D
L_Bloody_Swamp	= $3E
L_Scorpion_Isle	= $3F
L_Tower_of_Blood	= $40
L_The_Crypt	= $41
L_Alien_Twilight	= $42
L_Tunnel_Beneath_the_Woods	= $43
L_Hills_of_Forever	= $44
L_Monster_Island	= $45
L_The_Shimmering_Caves	= $46
L_The_Crypt_47	= $47 ; unplayable
L_Sky_Fortress	= $48
L_Elsewhere_1	= $49
L_Elsewhere_2	= $4A
L_Elsewhere_3	= $4B
L_Elsewhere_5	= $4D
L_Elsewhere_6	= $4E
L_Elsewhere_7	= $4F
L_Elsewhere_8	= $50
L_Elsewhere_10	= $51
L_Elsewhere_9	= $52
L_Elsewhere_11	= $53
L_Elsewhere_12	= $54
L_Elsewhere_13	= $55
L_Elsewhere_14	= $56
L_Elsewhere_32	= $57
L_Elsewhere_16	= $58
L_Elsewhere_15	= $59
L_Elsewhere_17	= $5A
L_Elsewhere_19	= $5B
L_Elsewhere_18	= $5C
L_Elsewhere_22	= $5D
L_Elsewhere_20	= $5E
L_Elsewhere_21	= $5F
L_Elsewhere_23	= $60
L_Elsewhere_24	= $61
L_Elsewhere_25	= $62
L_Elsewhere_26	= $63
L_Elsewhere_27	= $64
L_Elsewhere_28	= $65
L_Elsewhere_29	= $66
L_Elsewhere_30	= $67
L_Elsewhere_31	= $68

; Levels by map number
M_Under_Skull_Mountain_2	= 0
M_Under_Skull_Mountain_1	= 1
M_Under_Skull_Mountain_3	= 2
M_Stairway_to_Obilivion	= 3
M_The_Black_Pit	= 4
M_Plethora	= 5
M_Elsewhere_23	= 8
M_The_Cliffs_of_Illusion	= $A
M_Knights_Isle	= $B
M_Whale_Grotto	= $C
M_Coral_Blade_Grotto	= $D
M_Isl_of_the_Lion_Lord	= $E
M_Crab_Cove	= $F
M_Alien_Isle	= $10
M_Monster_Island	= $11
M_Scorpion_Isle	= $12
M_Shishkaboss	= $13
M_Devils_March_1	= $14
M_Bloody_Swamp	= $15
M_Devils_March_2	= $16
M_Alien_Twilight	= $17
M_Wind_City	= $18
M_Forced_Entry	= $19
M_unused_1A	= $1A
M_The_Deadly_Skyscrapers	= $1C
M_Sinister_Sewers	= $1D
M_Skydragon_Castle_2	= $21
M_Tower_of_Blood	= $22
M_Wind_Castles_1	= $25
M_Wind_Castles_2	= $26
M_Skydragon_Castle_1	= $27
M_Stormwalk_Mountain	= $2B
M_Dragonspike	= $2C
M_Highwater_Pass_1	= $2D
M_Highwater_Pass_2	= $2E
M_The_Nightmare_Peaks_1	= $2F
M_The_Pinnacle	= $30
M_The_Nightmare_Peaks_2	= $31
M_The_Caged_Beast	= $32
M_Secret_in_the_Rocks	= $33
M_Madmaze_Mountain	= $34
M_Blizzard_Mountain	= $35
M_Frosty_Doom	= $36
M_The_Crystal_Crags_2	= $37
M_The_Final_Marathon	= $38
M_The_Shimmering_Caves	= $39
M_Ice_Gods_Vengeance	= $3A
M_Diamond_Edge	= $3B
M_Sky_Fortress	= $3C
M_The_Crystal_Crags_1	= $3D
M_Caves_of_Ice	= $3E
M_Hoverboard_Beach	= $3F
M_Pyramids_of_Peril	= $40
M_The_Crypt	= $41
M_The_Crypt_42	= $42 ; unplayable
M_The_Forbidden_Tombs	= $47
M_The_Crypt_48	= $48 ; unplayable
M_The_Whispering_Woods_2	= $49
M_Blue_Lake_Woods_1	= $4A
M_Blue_Lake_Woods_2	= $4B
M_The_Whispering_Woods_1	= $4C
M_Woods_of_Despair_2	= $4D
M_Tunnel_Beneath_the_Woods	= $4E
M_Woods_of_Despair_1	= $4F
M_The_Valley_of_Life	= $53
M_Hills_of_the_Warrior_1	= $54
M_Hidden_Canyon	= $55
M_Hills_of_the_Warrior_2	= $56
M_Beneath_the_Twisted_Hills	= $57
M_Hills_of_Forever	= $58
M_The_Land_Below	= $59
M_The_Hills_Have_Eyes	= $5A
M_Lions_Den	= $5C
M_Elsewhere_5	= $5D
M_Elsewhere_2	= $5E
M_Elsewhere_3	= $5F
M_Elsewhere_1	= $61
M_Elsewhere_6	= $62
M_Elsewhere_17	= $63
M_Elsewhere_7	= $64
M_Elsewhere_19	= $65
M_Elsewhere_11	= $66
M_Elsewhere_8	= $67
M_Elsewhere_12	= $68
M_Elsewhere_18	= $69
M_Elsewhere_22	= $6A
M_Elsewhere_20	= $6B
M_Boomerang_Bosses	= $6C
M_Elsewhere_13	= $6D
M_Elsewhere_10	= $6E
M_Elsewhere_14	= $6F
M_Elsewhere_32	= $70
M_Elsewhere_21	= $71
M_Elsewhere_29	= $72
M_Elsewhere_30	= $73
M_Bagel_Brothers	= $74
M_Elsewhere_9	= $75
M_Elsewhere_31	= $76
M_Elsewhere_16	= $77
M_Elsewhere_15	= $78
M_Elsewhere_28	= $79
M_Elsewhere_26	= $7A
M_Elsewhere_27	= $7B
M_Elsewhere_24	= $7C
M_Elsewhere_25	= $7D